---
- name: Update APT package cache
  action: apt update_cache=yes

- name: Upgrade APT to the lastest packages
  action: apt upgrade=safe

- name: Install mosh
  action: apt pkg=mosh state=installed

- name: Install vim
  action: apt pkg=vim state=installed

- name: Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

- name: Install logwatch
  action: apt pkg=logwatch state=installed

- name: Make logwatch mail $logwatch_email daily
  lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes

- name: Setup ufw ssh
  action: shell ufw allow 22/tcp

- name: Setup ufw http
  action: shell ufw allow 80/tcp

- name: Setup ufw https
  action: shell ufw allow 443/tcp

- name: Setup ufw
  action: shell ufw allow 60023/udp

- name: Enable ufw
  action: shell echo 'y' | ufw enable

- name: Sysctl Hardening
  sysctl: name={{ item.name }} value={{ item.value }}
  with_items:
    - { name: "net.ipv4.conf.all.rp_filter", value: 1 }
    - { name: "net.ipv4.conf.default.rp_filter", value: 1 }
    - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: 1 }
    - { name: "net.ipv4.conf.all.accept_source_route", value: 0 }
    - { name: "net.ipv6.conf.all.accept_source_route", value: 0 }
    - { name: "net.ipv4.conf.default.accept_source_route", value: 0 }
    - { name: "net.ipv6.conf.default.accept_source_route", value: 0 }
    - { name: "net.ipv4.conf.all.send_redirects", value: 0 }
    - { name: "net.ipv4.conf.default.send_redirects", value: 0 }
    - { name: "net.ipv4.tcp_syncookies", value: 1 }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 2048 }
    - { name: "net.ipv4.tcp_synack_retries", value: 2 }
    - { name: "net.ipv4.conf.all.log_martians", value: 1 }
    - { name: "net.ipv4.icmp_ignore_bogus_error_responses", value: 1 }
    - { name: "net.ipv4.conf.all.accept_redirects", value: 0 }
    - { name: "net.ipv6.conf.all.accept_redirects", value: 0 }
    - { name: "net.ipv4.conf.default.accept_redirects", value: 0 }
    - { name: "net.ipv6.conf.default.accept_redirects", value: 0 }
    - { name: "net.ipv4.icmp_echo_ignore_all", value: 1 }
