---
- name: Create swap file
  command: dd if=/dev/zero of={{ swap.file_path }} bs=1MB count={{ swap.file_size_mb }}
           creates="{{ swap.file_path }}"

- name: Change swap file permissions
  file: path="{{ swap.file_path }}"
        owner=root
        group=root
        mode=0600

- name: Check swap file type
  command: file {{ swap.file_path }}
  register: swapfile

- name: Make swap file
  command: sudo mkswap {{ swap.file_path }}
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap.file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: "swapon {{ swap.file_path }}"
  when: ansible_swaptotal_mb < 1
