---
- hosts: all
  sudo: true
  vars_files:
    - vars/defaults.yml

  tasks:
    - name: Add the deploy user
      user: name={{ deploy.user }}
            home=/home/{{ deploy.user }}
            shell=/bin/bash
            comment="Deploy User"
            groups=sudo

    - authorized_key: user={{ deploy.user }} key="{{ pubkey_path }}"

    - name: Add user remote to sudoers
      lineinfile:
        "dest=/etc/sudoers
        regexp='^{{ deploy.user }} ALL'
        line='{{ deploy.user }} ALL=(ALL) NOPASSWD: ALL'
        state=present"

    - name: Disallow root SSH access
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PermitRootLogin"
        line="PermitRootLogin no"
        state=present
      notify:
        - restart sshd

    - name: Disallow SSH password authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication no"
        state=present
      notify:
        - restart sshd

    - name: Disallow SSH GSS API authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^GSSAPIAuthentication"
        line="GSSAPIAuthentication no"
        state=present
      notify:
        - restart sshd

  handlers:
  - name: restart sshd
    service:
      name=ssh
      state=restarted
