- name: Add puma-manager
  template: src=puma-manager.j2 dest=/etc/init/puma-manager.conf force=yes mode=755
  tags: puma

- name: Add puma config
  template: src=etc_puma.conf.j2 dest=/etc/puma.conf force=yes mode=755
  tags: puma

- name: Add puma init scrinitp
  template: src=etc_init_puma.j2 dest=/etc/init/puma.conf force=yes mode=755
  tags: puma

- name: Add puma shared/config
  template: src=puma.rb.j2 dest={{deploy.directory}}/shared/config/puma.rb force=yes mode=755 owner={{deploy.user}} group={{deploy.group}}
  tags: puma

- name: Make shared/tmp/sockets
  file: path={{deploy.directory}}/shared/tmp/sockets state=directory owner={{deploy.user}} group={{deploy.group}}
  tags: tmp

- name: Restart puma-manager
  action: service name={{puma.service}} state=restarted
